# Generated by Django 2.2.5 on 2020-04-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='lorem_ipsum'),
        ),
    ]
